using UnityEngine;

#nullable enable

namespace OpenRCT2.Generators.Map.Data
{
    /// <summary>
    /// Specifies how a track piece should be generated by the <see cref="TrackGenerator"/>.
    /// </summary>
    public readonly struct TrackPieceOptions
    {
        /// <summary>
        /// Specifies how to generate this track piece.
        /// </summary>
        public readonly TrackPieceGenerationStrategy generationStrategy;


        /// <summary>
        /// Specifies the mesh that should be used.
        /// </summary>
        public readonly Mesh? mesh;


        public TrackPieceOptions(TrackPieceGenerationStrategy generationStrategy, Mesh? mesh)
        {
            this.generationStrategy = generationStrategy;
            this.mesh = mesh;
        }
    }
}
