using UnityEngine;

namespace Generation.Retro
{
    /// <summary>
    /// Specifies how a track piece should be generated by the
    /// <see cref="TrackGenerator"/>.
    /// </summary>
    public class TrackPieceOptions
    {
        /// <summary>
        /// Specifies how to generate this track piece.
        /// </summary>
        public TrackPieceGenerationStrategy GenerationStrategy;


        /// <summary>
        /// Specifies the mesh that should be used.
        /// </summary>
        public Mesh Mesh;
    }
}
