namespace OpenRCT2.Unity
{
    public enum PeepActionSprite : byte
    {
        None = 0,
        Check_Time = 1,
        Watch_Ride = 2,
        Eat_Food = 3,
        Shake_Head = 4,
        Empty_Pockets = 5,
        Hold_Mat = 6,
        Sitting_Idle = 7,
        Sitting_Eat_Food = 8,
        Sitting_Look_Around_Left = 9,
        Sitting_Look_Around_Right = 10,
        UI = 11,
        Staff_Mower = 12,
        Wow = 13,
        Throw_Up = 14,
        Jump = 15,
        Staff_Sweep = 16,
        Drowning = 17,
        Staff_Answer_Call = 18,
        Staff_Answer_Call_2 = 19,
        Staff_Checkboard = 20,
        Staff_Fix = 21,
        Staff_Fix_2 = 22,
        Staff_Fix_Ground = 23,
        Staff_Fix_3 = 24,
        Staff_Watering = 25,
        Joy = 26,
        Read_Map = 27,
        Wave = 28,
        Staff_Empty_Bin = 29,
        Wave_2 = 30,
        Take_Photo = 31,
        Clap = 32,
        Disgust = 33,
        Draw_Picture = 34,
        Being_Watched = 35,
        Withdraw_Money = 36,
        Invalid = 255
    };
}
