namespace OpenRCT
{
    public enum PeepActionSprite : byte
    {
        None = 0,
        CheckTime = 1,
        WatchRide = 2,
        EatFood = 3,
        ShakeHead = 4,
        EmptyPockets = 5,
        HoldMat = 6,
        SittingIdle = 7,
        SittingEatFood = 8,
        SittingLookAroundLeft = 9,
        SittingLookAroundRight = 10,
        UI = 11,
        StaffMower = 12,
        Wow = 13,
        ThrowUp = 14,
        Jump = 15,
        StaffSweep = 16,
        Drowning = 17,
        StaffAnswerCall = 18,
        StaffAnswerCall2 = 19,
        StaffCheckboard = 20,
        StaffFix = 21,
        StaffFix2 = 22,
        StaffFixGround = 23,
        StaffFix3 = 24,
        StaffWatering = 25,
        Joy = 26,
        ReadMap = 27,
        Wave = 28,
        StaffEmptyBin = 29,
        Wave2 = 30,
        TakePhoto = 31,
        Clap = 32,
        Disgust = 33,
        DrawPicture = 34,
        BeingWatched = 35,
        WithdrawMoney = 36,
        Invalid = 255
    };
}
